---

tomcat_version: "8.5.27"

tomcat_mirrors:
  - http://archive.apache.org/dist/tomcat

# Temporary Storage Directory
tomcat_tmp_storage: /tmp/tomcat-ansible

java_home: /usr/java/latest

# Variable That Decides To Install the APR Role Dependency
tomcat_use_apr: true

tomcat_user_name: tomcat
tomcat_user_group: tomcat
tomcat_user_home: /home/{{ tomcat_user_name }}
tomcat_user_system: false

tomcat_port_shutdown: 8005
tomcat_port_connector: 8080
tomcat_port_redirect: 8443
tomcat_port_ajp: 8009

tomcat_java_opts: ""
tomcat_catalina_opts: ""

tomcat_base_dir: /opt
tomcat_catalina_home: "{{ tomcat_base_dir }}/tomcat"
tomcat_instance_path: "{{ tomcat_base_dir }}/tomcat"

tomcat_prefer_ipv4: true
tomcat_override_uri_encoding: ""
tomcat_prefer_urandom: true

# install service with initctl / systemd
tomcat_install_service: true

tomcat_instance: tomcat

tomcat_roles:
  - manager
  - manager-gui
  - manager-script
  - manager-jmx
  - admin
  - admin-gui
  - admin-script

tomcat_users: []
  # - name: tomcat
  #   password: tomcat
  #   roles: "manager-gui,admin-gui"
  #

tomcat_debug: false

# This Edits And Allows Ansible To Configure These
# Otherwise it does a default install
tomcat_configure: true
tomcat_configure_configs: "{{ tomcat_configure }}"
tomcat_configure_libs: "{{ tomcat_configure }}"
tomcat_configure_webapps: "{{ tomcat_configure }}"

# These copy files across and will use basename
tomcat_extra_libs_path: []
tomcat_webapps_path: []

#Removes ROOT webapp Context if false
tomcat_root_context: false
tomcat_manager_context: false
tomcat_hostmanager_context: false
tomcat_docs_context: false
tomcat_examples_context: false

# Strings That Allow you to modify your
# tomcat instance in a predictable fashion.
tomcat_extra_global_naming_resources: ""
tomcat_context_xml_header_extra: ""
tomcat_context_xml_extra: ""


# Disable or enable session persistence
tomcat_disable_persistence_across_restarts: false

# Custom Configuration Files
tomcat_use_custom_server_xml: false
# tomcat_custom_server_xml: Path
tomcat_use_custom_web_xml: false
# tomcat_custom_web_xml: Path
tomcat_use_custom_context_xml: false
# tomcat_custom_context_xml: Path
tomcat_use_custom_tomcat_users_xml: false
# tomcat_custom_tomcat_users_xml: Path
tomcat_use_custom_manager_context_xml: false
# tomcat_custom_manager_context_xml: Path

# Tomcat major version
tomcat_version_major: "{{ tomcat_version.0 }}"
tomcat_tar_archive: "apache-tomcat-{{ tomcat_version }}.tar.gz"

tomcat_instance_directories:
  - conf
  - logs
  - webapps
  - temp
  - bin
  - lib
  - work

tomcat_version_specific:
  "8.5.27":
    checksum: md5:2d39cb3293ec3308d5235004adf0d134
    web_xml_schema_version: 3.1
    tomcat_native_version: "1.2.12"
  "9.0.0.M18":
    checksum: md5:626e16b93de65b2a58714ed50f00d9f9
    web_xml_schema_version: 3.1
    tomcat_native_version: "1.2.12"
